[package]
name = "nft_relayer"
version = "1.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
sled = "0.34.2"
anyhow = "1.0.75"
dotenv = "0.15.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.68"
ethers = { version = "2.0.10", features = ["abigen"] }
email-wallet-utils = { path = "../utils" }
axum = "0.6.20"
rand = "0.8.5"
reqwest = "0.11.22"
hex = "0.4.3"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_warn",
] }
relayer = { path = "../relayer" }
base64 = "0.21.7"
chrono = "0.4.31"
ff = { version = "0.13.0", default-features = false, features = ["std"] }

# wasm-bindgen = { version = "0.2.90", default-features = false }
# wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen.git", tag = "0.2.88", default-features = false }


[build-dependencies]
ethers = "2.0.10"
chrono = "0.4"
